---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "05/19/2022"

quarter <- "Spring2022"

week_folder <- "05-19_Pan"


title <- "How Information Flows from the World to China"


speaker <- "Jennifer Pan"
department <- "Associate Professor of Communication and, by courtesy, of Political Science and of Sociology"
university <- "Stanford University"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Spring2022/issues/7"

#Papers
week_paper_ref0 <- "Lu, Y., Schaefer, J., Park, K., Joo, J., & Pan, J. (2021). How Information Flows from the World to China. working paper."
week_paper_file0 <- "inflow.pdf"


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")


```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** A large body of research shows that government censorship—internet shutdowns, blockages, firewalls—impose significant barriers to the transnational flow of information despite the connective power of digital technologies. In this paper, we examine whether and how information flows across borders despite government censorship. We develop a semi-automated system that combines deep learning and human annotation to find co-occurring content across different social media platforms and languages. We use this system to detect co-occurring content between Twitter and Sina Weibo as Covid-19 spread globally, and we conduct in-depth investigations of co-occurring content to identify those that constitute an inflow of information from the global information ecosystem into China. We find that approximately one-fifth of content with relevance for China that gain widespread public attention on Twitter appear on Weibo. Unsurprisingly, Chinese state-controlled media and commercialized domestic media play a dominant role in facilitating these inflows of information. However, we also find that Weibo users
without media or government affiliation are consistently transmitting global information to China, and in limited instances, foreign governments and media outlets also transmit information directly to Weibo. These results imply that while China’s censorship apparatus severely limits the inflow of global information into China, state-controlled and domestic media outlets do not completely dominate information transmitted into the country.

</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 9:30am-10:50am </h4>

<br><br>

<p class=footertext2>

**Jennifer Pan** is an Associate Professor of Communication at Stanford University. Her research focuses on political communication and authoritarian politics. Pan uses experimental and computational methods with large-scale datasets on political activity in China and other authoritarian regimes to answer questions about how autocrats perpetuate their rule. How political censorship, propaganda, and information manipulation work in the digital age. How preferences and behaviors are shaped as a result.

Her book, Welfare for Autocrats: How Social Assistance in China Cares for its Rulers (Oxford, 2020) shows how China's pursuit of political order transformed the country’s main social assistance program, Dibao, for repressive purposes. Her work has appeared in peer reviewed publications such as the American Political Science Review, American Journal of Political Science, Comparative Political Studies, Journal of Politics, and Science.

She graduated from Princeton University, summa cum laude, and received her Ph.D. from Harvard University’s Department of Government.


</p>

<br>

<p class=footertext2>

**Attendance**: The talk will be held in person in room 295 of 1155 E 60th Street.

</p>

<p class=footertext2>

**Participation**: Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting an individual question or comment on the issues <a href= `r issues_url`> page </a> of the <a href="https://github.com/uchicago-computation-workshop"> workshop's public repository.</a>

This week's suggested readings:

- `r readings0`

<br>

<br><br>

---

<p class=footertext> The 2021-2022 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 9:30 a.m. to 10:50 a.m. All interested faculty and graduate students are welcome.</p>

<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a question or comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>

