---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "04/28/2022"

quarter <- "Spring2022"

week_folder <- "04-28_Wachter"


title <- "Unbiased AI in a biased world: mission (im) possible?"


speaker <- "Sandra Wachter"
department <- "Oxford Internet Institute"
university <- "University of Oxford"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Spring2022/issues/5"
zoom_url <- "https://uchicago.zoom.us/j/94541791231?pwd=UGlNalJTc0tVYkpwWTZSM1d0bld0QT09"

#Papers

week_paper_ref0 <- "Wachter, S., Mittelstadt, B., & Russell, C. (2021). Why fairness cannot be automated: Bridging the gap between EU non-discrimination law and AI. Computer Law & Security Review, 41, 105567."
week_paper_file0 <- "wachter_1.pdf"

week_paper_ref1 <- "Wachter, S., Mittelstadt, B., & Russell, C. (2020). Bias preservation in machine learning: the legality of fairness metrics under EU non-discrimination law. W. Va. L. Rev., 123, 735."
week_paper_file1 <- "wachter_2.pdf"


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")

```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** Western societies are marked by diverse and extensive biases and inequality that are unavoidably embedded in the data used to train machine learning. Algorithms trained on biased data will, without intervention, produce biased outcomes  and increase the inequality experienced by historically disadvantaged groups. Recognising this problem, much work has emerged in recent years to test for bias in machine learning and AI systems using various bias metrics. In this paper we assessed the compatibility of technical fairness metrics and tests used in machine learning against the aims and purpose of EU non-discrimination law.  We provide concrete recommendations including a user-friendly checklist for choosing the most appropriate fairness metric for uses of machine learning under EU non-discrimination law.

</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 9:30am-10:50am </h4>

<br><br>

<p class=footertext2>

**Sandra Wachter** is an Associate Professor and Senior Research Fellow focusing on law and ethics of AI, Big Data, and robotics as well as Internet and platform regulation at the Oxford Internet Institute at the University of Oxford. Her current research focuses on profiling, inferential analytics, explainable AI, algorithmic bias, diversity, and fairness, as well as governmental surveillance, predictive policing, human rights online, and health tech and medical law. At the OII, Professor Sandra Wachter leads and coordinates the Governance of Emerging Technologies (GET) Research Programme that investigates legal, ethical, and technical aspects of AI, machine learning, and other emerging technologies.


</p>

<br>

<p class=footertext2>

**Attendance**: The talk will be held virtually on Zoom. Please join via Zoom at the link provided: ([link](`r zoom_url`)).

</p>

<p class=footertext2>

**Participation**: Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting an individual question or comment on the issues <a href= `r issues_url`> page </a> of the <a href="https://github.com/uchicago-computation-workshop"> workshop's public repository.</a>

This week's readings:

- `r readings0`
- `r readings1`

<br>

<br><br>

---

<p class=footertext> The 2021-2022 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 9:30 a.m. to 10:50 a.m. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a question or comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
