---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "03/31/2022"

quarter <- "Spring2022"

week_folder <- "03-31_Evans"


title <- "The Social and Biographical Locus of Innovation"


speaker <- "James Evans"
department <- "Department of Sociology"
university <- "University of Chicago"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Spring2022/issues/1"


#Papers

week_paper_ref0 <- "Xu, F., Wu, L., & Evans, J. (2022). Flat Teams Drive Scientific Innovation. arXiv preprint arXiv:2201.06726."
week_paper_file0 <- "evans1.pdf"

week_paper_ref1 <- "Cui, H., Wu, L., & Evans, J. A. (2022). Aging Scientists and Slowed Advance. arXiv preprint arXiv:2202.04044."
week_paper_file1 <- "evans2.pdf"

#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")



```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** In this talk, I explore the social, biographical and demographical locus of innovation in science, scholarship and technological development. With teams growing in all areas of scientific and scholarly research, I first explore the relationship between team structure and the character of innvation they produce. Drawing on 89,575 self-reports of team member research activity underlying scientific publications, I show how individual activities cohere into broad roles of (1) leadership through the direction and presentation of research and (2) support through data collection, analysis and discussion. The hidden hierarchy of a scientific team is characterized by its lead (or L)-ratio of members playing leadership roles to total team size. The L-ratio is validated through correlation with imputed contributions to the specific paper and to science as a whole, which I use to effectively extrapolate the L-ratio for 16,397,750 papers where roles are not explicit. I show that relative to flat, egalitarian teams, tall, hierarchical teams produce less novelty and more often develop existing ideas; increase productivity for those on top and decrease it for those beneath; increase short-term citations but decrease long-term influence. These effects hold within-person -- the same person on the same-sized team produces science much more likely to disruptively innovate if they work on a flat, high L-ratio team. These results suggest the critical role flat teams play for sustainable scientific advance and the training and advancement of scientists. I then explore how with rising life expectancies around the world and an older scientific workforce than ever before, what aging means for individual scientists and what aging scientists mean for scientific progress? Prior research focuses on star scientists, their changing dates and rates of breakthrough success across history. I examine how all scientists and scholars age in terms of how their stream of ideas and contributions relate to the evolving frontier of knowledge, and how demographically aging fields relate to field-level progress. Analyzing more than 244 million scholars across 241 million articles over the last two centuries, here I show that for all fields, periods, and impact levels, scientists’ research ideas and references age over time, their research is less likely to disrupt the state of science and more likely to criticize emerging work. Early success accelerates scientist aging; while changing institutions and fields and collaborating with young scientists slows it. These patterns aggregate within fields such that those with a higher proportion of older scientists experience a lower churn of ideas and more rapid individual aging, suggesting a universal link between aging, activity, and advance.


</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 9:30am-10:50am </h4>

<br><br>

<p class=footertext2>

**James Evans** is a Professor in the Department of Sociology, Director of Knowledge Lab, and Co-Director for the Masters in Computational Social Science Program.

</p>

<br>

<p class=footertext2>

**Attendance**: The talk will be held in-person in room 295 of 1155 E 60th Street.
</p>

<p class=footertext2>

**Participation**: Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting an individual question or comment on the issues <a href= `r issues_url`> page </a> of the <a href="https://github.com/uchicago-computation-workshop"> workshop's public repository.</a>

This week's readings:

- `r readings0`
- `r readings1`


<br>

<br><br>

---

<p class=footertext> The 2021-2022 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 9:30 a.m. to 10:50 p.m. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a question or comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
