---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "05/05/2022"

quarter <- "Spring2022"

week_folder <- "05-05_Lazer"


title <- "Deplatforming Right-Wing Extremists on Twitter Following the January 6th Insurrection"


speaker <- "David Lazer"
department <- "University Distinguished Professor of Political Science and Computer Sciences"
university <- "Northeastern University"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Spring2022/issues/6"

#Papers
week_paper_ref0 <- "Hughes, A. G., McCabe, S. D., Hobbs, W. R., Remy, E., Shah, S., & Lazer, D. M. (2021). Using administrative records and survey data to construct samples of Tweeters and Tweets. Public Opinion Quarterly, 85(S1), 323-346."
week_paper_file0 <- "Lazer_2.pdf"

week_paper_ref1 <- "Grinberg, N., Joseph, K., Friedland, L., Swire-Thompson, B., & Lazer, D. (2019). Fake news on Twitter during the 2016 US presidential election. Science, 363(6425), 374-378."
week_paper_file1 <- "Lazer_2.pdf"


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")

```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** What happened when Twitter deplatformed 70,000 right-wing extremists following the January 6 insurrection? Using a panel of over a half million active Twitter users and a sharp regression discontinuity design, we test the causal effects of this intervention on the circulation of misinformation by those deplatformed, and by users from adjacent groups such as misinformation supersharers, QAnon traffickers and deplatformed users’ followers. We show that Twitter's intervention reduced misinformation on the site substantially by preventing the deplatformed users from spreading it. We also show that similar, non-deplatformed users exited the platform in response to the intervention. The results inform the historical record of the insurrection, a momentous event in U.S. history, and show the capacity of social media platforms to control public discourse.

</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 9:30am-10:50am </h4>

<br><br>

<p class=footertext2>

**David Lazerr** is a University Distinguished Professor of Political Science and Computer Sciences, Northeastern University, and Co-Director, NULab for Texts, Maps, and Networks. Prior to coming to Northeastern University, he was on the faculty at the Harvard Kennedy School (1998-2009). In 2019, he was elected a fellow to the National Academy of Public Administration. His research has been published in such journals as Science, Nature, Proceedings of the National Academy of Science, the American Political Science Review, Organization Science, and the Administrative Science Quarterly, and has received extensive coverage in the media, including the New York Times, NPR, the Washington Post, the Wall Street Journal, and CBS Evening News.

He is among the leading scholars in the world on misinformation and computational social science and has served in multiple leadership and editorial positions, including as a board member for the International Network of Social Network Analysts (INSNA), reviewing editor for Science, associate editor of Social Networks and Network Science, numerous other editorial boards and program committees.


</p>

<br>

<p class=footertext2>

**Attendance**: The talk will be held in person in room 295 of 1155 E 60th Street.

</p>

<p class=footertext2>

**Participation**: Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting an individual question or comment on the issues <a href= `r issues_url`> page </a> of the <a href="https://github.com/uchicago-computation-workshop"> workshop's public repository.</a>

This week's readings:

- `r readings0`
- `r readings1`

<br>

<br><br>

---

<p class=footertext> The 2021-2022 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 9:30 a.m. to 10:50 a.m. All interested faculty and graduate students are welcome.</p>

<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a question or comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>

