---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "04/21/2022"

quarter <- "Spring2022"

week_folder <- "04-21_Wang"


title <- "Out of Scope, Out of Mind: Expanding Frontiers for Fair ML in Social Decision Making"


speaker <- "Serena Wang"
department <- "Computer Science"
university <- "University of California, Berkeley"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Spring2022/issues/4"


#Papers

week_paper_ref0 <- "Serena Wang, Wenshuo Guo, Harikrishna Narasimhan, Andrew Cotter, Maya R. Gupta, Michael I. Jordan. Robust Optimization for Fairness with Noisy Protected Groups. 34th Conference on Neural Information Processing Systems (NeurIPS), 2020."
week_paper_file0 <- "wang_1.pdf"

week_paper_ref1 <- "Serena Wang, Maya R. Gupta. Deontological Ethics By Monotonicity Shape Constraints. Proceedings of The 23nd International Conference on Artificial Intelligence and Statistics (AISTATS), 2020."
week_paper_file1 <- "wang_reading2.pdf"

week_paper_ref2 <- "Waters, Austin, and Risto Miikkulainen. Grade: Machine learning support for graduate admissions. Ai Magazine 35.1 (2014): 64-64."
week_paper_file2 <- "wang_3.pdf"

#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")

readings2 <- paste0("[", week_paper_ref2,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file2,")")
```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** Recent literature in fair machine learning (fair ML) has focused on applying notions of fairness within a technical scope involving data, models, and prediction quality across protected groups. This talk will start by presenting two technical solutions within this framework to overcome practical challenges, including (i) enforcing group-based fairness constraints when the data is incomplete or noisy, and (ii) avoiding unfair penalization of other input features. Still, beyond these practical challenges, even the most heavily fairness-constrained ML model might fall short in satisfying societal needs due to choices in problem formulation and downstream interventions. Thus, based on qualitative work in the education domain, we expand the scope of the ML life cycle and suggest opportunities beyond the typical fairness paradigms for technical and interdisciplinary contribution.

</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 9:30am-10:50am </h4>

<br><br>

<p class=footertext2>

**Serena Wang** is a fourth-year PhD student in Computer Science at University of California, Berkeley, advised by Prof. Rediet Abebe and Prof. Michael I. Jordan. Serena's research interests include understanding and improving the long term societal impacts of machine learning by rethinking ML algorithms and practices. On the algorithmic side, Serena employs tools from robust optimization, constrained optimization, and statistical learning theory. Serena has also concurrently held a 20% collaboration with Google Research where Serena has worked on improving ML interpretability and controllability. Serena is supported by the NSF Graduate Research Fellowship.


</p>

<br>

<p class=footertext2>

**Attendance**: The talk will be held in-person in room 295 of 1155 E 60th Street.
</p>

<p class=footertext2>

**Participation**: Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting an individual question or comment on the issues <a href= `r issues_url`> page </a> of the <a href="https://github.com/uchicago-computation-workshop"> workshop's public repository.</a>

This week's readings:

- `r readings0`
- `r readings1`
- `r readings2`

<br>

<br><br>

---

<p class=footertext> The 2021-2022 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 9:30 a.m. to 10:50 a.m. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a question or comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
